from typing import TYPE_CHECKING, Optional

from redisvl.extensions.cache.llm import SemanticCache
from redisvl.utils.vectorize.base import BaseVectorizer

if TYPE_CHECKING:
    from preparation_pipeline.embedder import BgeM3Embedder


class BgeM3CacheVectorizer(BaseVectorizer):
    """Describe externally generated BGE-M3 vectors to RedisVL."""

    model: str = "BAAI/bge-m3"
    dims: int = 1024

    def _embed(self, content, **kwargs):
        raise NotImplementedError("BGE-M3 vectors are generated by BgeM3Embedder")


class ChatSemanticCache:
    def __init__(
        self,
        redis_url: str,
        embedder: "BgeM3Embedder",
        distance_threshold: float = 0.1,
        ttl_seconds: Optional[int] = 86400,
    ):
        self._embedder = embedder
        self._cache = SemanticCache(
            name="qa_semantic_cache_bge_m3",
            redis_url=redis_url,
            distance_threshold=distance_threshold,
            vector_dims=1024, #
            ttl=ttl_seconds,
            vectorizer=BgeM3CacheVectorizer(),
            overwrite=True, #
        )

    def check(self, question: str) -> Optional[str]:
        vector = self._embedder.embed_one(question).dense
        hits = self._cache.check(vector=vector, num_results=1)
        return hits[0]["response"] if hits else None

    def store(self, question: str, answer: str):
        vector = self._embedder.embed_one(question).dense
        self._cache.store(prompt=question, response=answer, vector=vector)

    def invalidate_all(self):
        """Gọi khi nội dung nguồn thay đổi nhiều, tránh trả lời dựa trên dữ liệu cũ."""
        self._cache.clear()
